### ISSUE TITLE
Twitter emoji update

### ISSUE THREAD

**Issue by fredvollmer** [iamcal/emoji-data#138] opened 2018-04-20 17:08 UTC
Hi, thanks for this wonderful library! Is there any chance of updating twitter emoji to 2.6.0? I might be able to lend a hand if I could be of any help.

**Comment by meganweller21** [comment] 2018-07-26 19:36
Any update on this?

**Comment by Art4** [comment] 2018-08-22 06:41
Unicode 11 (and Emoji 11.0) was released on June 5, 2018, see http://blog.unicode.org/2018/06/announcing-unicode-standard-version-110.html
It definded some new Emojis, see https://www.unicode.org/emoji/charts/emoji-released.html

Twemoji released version 11.0 also on June 5, 2018 and is now on version 11.1
All new emojis are supported in Twemoji 11, so it would be nice, if we could have an update.

I've imported the twemoji files by myself but I've noticed that the new emojis are missing in `emoji.json`, so they were not imported. How can I update the `emoji.json` for Unicode 11?

Btw: this issue is a duplicate of #112.

**Comment by tankerkiller125** [comment] 2019-05-10 23:48
Temoji is now on 12.0.5, it appears that they only update the SVG images now which breaks the scripts that currently exist, someone with better skills than I may need to create a script to convert the SVG to 72x72 png so that the rest of the Emoji script can update properly.

**Comment by iamcal** [comment] 2020-01-10 05:19
Twemoji v12.1.4 in supported in #165

**Comment by iamcal** [comment] 2020-01-11 04:52
fixed in v5.0.0

**Closed by iamcal** 2020-01-11 04:52 UTC
